[package]
name = "nmidi-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nmidi-protocol = { path = "../nmidi-protocol" }
tokio.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
mdns-sd.workspace = true
anyhow.workspace = true
hostname.workspace = true
