[package]
name = "nmidi-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nmidi-protocol = { path = "../nmidi-protocol" }
tokio.workspace = true
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
mdns-sd.workspace = true
midir.workspace = true
clap.workspace = true
anyhow.workspace = true
